//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicRater.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MusicRater.Tests.TestData", typeof(TestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Tracks&gt;
        ///   &lt;Track Author=&quot;a&quot; Title=&quot;t&quot; Url=&quot;u&quot; Listens=&quot;1&quot; IsExcluded=&quot;false&quot;&gt;
        ///      &lt;Comments&gt;liked it&lt;/Comments&gt;
        ///      &lt;SubRatings&gt;
        ///         &lt;SubRating Name=&quot;Criteria 1&quot; Value=&quot;5&quot; Weight=&quot;1&quot; /&gt;
        ///         &lt;SubRating Name=&quot;Criteria 2&quot; Value=&quot;6&quot; Weight=&quot;2&quot; /&gt;
        ///         &lt;SubRating Name=&quot;Criteria 3&quot; Value=&quot;7&quot; Weight=&quot;3&quot; /&gt;
        ///      &lt;/SubRatings&gt;
        ///   &lt;/Track&gt;
        ///&lt;/Tracks&gt;.
        /// </summary>
        internal static string OneTrackXml {
            get {
                return ResourceManager.GetString("OneTrackXml", resourceCulture);
            }
        }
    }
}
